Test: build Symbolic semantics

diff --git a/Test b/Test
--- a/Test
+++ b/Test
@@ -2,17 +2,34 @@
 
 set -euo pipefail
 
-die() {
-    echo >&2 -e "fatal:" "$@"
-    exit 1
-}
+announce()  { echo     -e '\n\n---- ' "$@";         }
+die()       { echo >&2 -e "fatal:" "$@"; exit 1;    }
 
 
 # Checks
 # ------
 
+submodules=(tests/ethereum-tests kevm-pyk/src/kevm_pyk/kproj/plugin
+            deps/metropolis web/k-web-theme
+)
+check_submodules() {
+    for s in "${submodules[@]}"; do
+        (cd "$s" && [[ -e '.git' ]]) ||
+            die "Git submodule '$s' not initialized.\n Initialize with:\n\n\tgit submodule update --init --recursive"
+        git diff  --exit-code --ignore-submodules=none "$s" ||
+            die "Git submodule '$s' is modified. Use 'git add' to cache this change, or update modules with:\n\n\tgit submodule update --init --recursive"
+    done
+}
+
+check_clang_version() {
+    minimum_version="15.0.0"
+    actual_version="$(clang --version | head -n 1 | cut -d' ' -f 3)"
+    [[  "$minimum_version" = $(echo -e "$minimum_version\n$actual_version" | sort -V | head -n1) ]] ||
+        die "Clang version $minimum_version or higher needed."
+}
+
 check_k() {
-    update='\n\tkup shell k --version v$(cat deps/k_release)'
+    update='\n\tkup shell k.openssl --version v$(cat deps/k_release)'
     type kompile 2>/dev/null >/dev/null \
         || die 'K not found in path.' \
                '\nInstall with:' "$update"
@@ -27,25 +44,16 @@ check_k() {
                '\nUpdate with:' "$update"
 }
 
-submodules=(tests/ethereum-tests kevm-pyk/src/kevm_pyk/kproj/plugin
-            deps/metropolis web/k-web-theme
-)
-check_submodules() {
-    for s in "${submodules[@]}"; do
-        (cd "$s" && [[ -e '.git' ]]) ||
-            die "Git submodule '$s' not initialized.\n Initialize with:\n\n\tgit submodule update --init --recursive"
-        git diff  --exit-code --ignore-submodules=none "$s" ||
-            die "Git submodule '$s' is modified. Use 'git add' to cache this change, or update modules with:\n\n\tgit submodule update --init --recursive"
-    done
+# Builders
+# --------
+
+build_with_kdist() {
+    declare -g verbose
+    poetry -C kevm-pyk run kdist $verbose build "$@" > /dev/null ||
+        die "Building blockchain plugin failed. Run with '-v'for logs"
 }
 
 
-check_clang_version() {
-    minimum_version="15.0.0"
-    actual_version="$(clang --version | head -n 1 | cut -d' ' -f 3)"
-    [[  "$minimum_version" = $(echo -e "$minimum_version\n$actual_version" | sort -V | head -n1) ]] ||
-        die "Clang version $minimum_version or higher needed."
-}
 # Main
 # ----
 
@@ -54,6 +62,16 @@ check_clang_version() {
 # to access project github dependencies, or enable SSH keys?
 export PYTHON_KEYRING_BACKEND=keyring.backends.fail.Keyring
 
+verbose=
+[[ $# -gt 0 ]] && [[ $1 = '-v' ]] && verbose=--verbose
+
 check_submodules
 check_k
 check_clang_version
+
+announce 'Setting up Python dependencies';   make -s poetry
+announce 'Building Blockchain Plugin';       build_with_kdist "evm-semantics.plugin"
+announce 'Building Symbolic Semantics';      build_with_kdist "evm-semantics.haskell"
+
+# TODO: Hangs up, possibly due to a race in KDist?
+# announce 'Building Concrete Semantics';      build_with_kdist "evm-semantics.llvm"
